INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Blizzard World", "Hybrid", 2);
INSERT INTO game_map (name, gameType, gameTypeId, subMap1, subMap2, subMap3) VALUES ("Busan", "Control", 3, "Downtown", "Sanctuary", "MEKA Base");
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Dorado", "Escort", 1);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Eichenwalde", "Hybrid", 2);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Hanamura", "Assault", 0);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Havana", "Escort", 1);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Hollywood", "Hybrid", 2);
INSERT INTO game_map (name, gameType, gameTypeId, subMap1, subMap2, subMap3) VALUES ("Ilios", "Control", 3, "Lighthouse", "Ruins", "Well");
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Junkertown", "Escort", 1);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("King's Row", "Hybrid", 2);
INSERT INTO game_map (name, gameType, gameTypeId, subMap1, subMap2, subMap3) VALUES ("Lijiang Tower", "Control", 3, "Night Market", "Garden", "Control Center");
INSERT INTO game_map (name, gameType, gameTypeId, subMap1, subMap2, subMap3) VALUES ("Nepal", "Control", 3, "Village", "Shrine", "Sanctum");
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Numbani", "Hybrid", 2);
INSERT INTO game_map (name, gameType, gameTypeId, subMap1, subMap2, subMap3) VALUES ("Oasis", "Control", 3, "City Center", "Gardens", "University");
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Rialto", "Escort", 1);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Route: 66", "Escort", 1);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Temple of Anubis", "Assault", 0);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Volskaya Industries", "Assault", 0);
INSERT INTO game_map (name, gameType, gameTypeId) VALUES ("Watchpoint: Gibraltar", "Escort", 1);
